<?php

namespace FondOfOryx\Zed\JellyfishAvailabilityAlert\Business\Dependency\Service;

use FondOfSpryker\Zed\Jellyfish\Dependency\Service\JellyfishToUtilEncodingServiceInterface;

interface JellyfishAvailabilityAlertToUtilEncodingServiceInterface extends JellyfishToUtilEncodingServiceInterface
{
}
