<?php

namespace FondOfOryx\Zed\ReturnLabelsRestApi\Business\Mapper;

use Codeception\Test\Unit;
use Generated\Shared\Transfer\RestReturnLabelRequestTransfer;
use Generated\Shared\Transfer\ReturnLabelRequestTransfer;

class ReturnLabelRequestMapperTest extends Unit
{
    /**
     * @var \FondOfOryx\Zed\ReturnLabelsRestApi\Business\Mapper\ReturnLabelRequestMapperInterface
     */
    protected $returnLabelRequestMapper;

    /**
     * @var \Generated\Shared\Transfer\RestReturnLabelRequestTransfer|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $restReturnLabelRequestTransferMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->restReturnLabelRequestTransferMock = $this->getMockBuilder(RestReturnLabelRequestTransfer::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->returnLabelRequestMapper = new ReturnLabelRequestMapper();
    }

    /**
     * @return void
     */
    public function testMapRestReturnLabelRequestToReturnLabelRequest(): void
    {
        $response = $this->returnLabelRequestMapper->mapRestReturnLabelRequestToReturnLabelRequest(
            $this->restReturnLabelRequestTransferMock
        );

        $this->assertInstanceOf(ReturnLabelRequestTransfer::class, $response);
    }
}
