<?php

namespace FondOfOryx\Shared\ReturnLabel;

interface ReturnLabelConstants
{
    public const API_BASE_URI = 'FOND_OF_ORYX:RETURN_LABEL:API_BASE_URI';
    public const API_USERNAME = 'FOND_OF_ORYX:RETURN_LABEL:API_USERNAME';
    public const API_PASSWORD = 'FOND_OF_ORYX:RETURN_LABEL:API_PASSWORD';
    public const API_RECEIVER_ID = 'FOND_OF_ORYX:RETURN_LABEL:API_RECEIVER_ID';
    public const API_REQUEST_TIMEOUT = 'FOND_OF_ORYX:RETURN_LABEL:API_REQUEST_TIMEOUT';
    public const API_REQUEST_HEADER = 'FOND_OF_ORYX:RETURN_LABEL:API_REQUEST_HEADER';

    public const APPEND_RETURN_FORM = 'FOND_OF_ORYX:RETURN_LABEL:APPEND_RETURN_FORM';
    public const PRINT_QR_CODE_ON_RETURN_FORM = 'FOND_OF_ORYX:RETURN_LABEL:PRINT_QR_CODE_ON_RETURN_FORM';
}
