<?php

namespace FondOfOryx\Shared\CrossEngage;

interface CrossEngageConstants
{
    public const CROSSENGAGE = 'CROSSENGAGE';
    public const TOKEN = 'token';
    public const QUERY_STRING = 'query-string';
    public const BASE_URL_YVES = 'BASE_URL_YVES';
    public const OPT_IN_PATH_PATTERN = 'OPT_IN_PATH_PATTERN';
    public const OPT_OUT_PATH_PATTERN = 'OPT_OUT_PATH_PATTERN';
    public const CROSSENGAGE_REDIRECT_PATTERN = 'CROSSENGAGE_REDIRECT_PATTERN';

    public const ROUTE_CROSSENGAGE_FOOTER = 'ROUTE_CROSSENGAGE_FOOTER';
    public const ROUTE_CROSSENGAGE_SUBMIT_FORM = 'ROUTE_CROSSENGAGE_SUBMIT_FORM';
    public const ROUTE_CROSSENGAGE_CONFIRM_SUBSCRIPTION = 'ROUTE_CROSSENGAGE_CONFIRM_SUBSCRIPTION';
    public const ROUTE_CROSSENGAGE_UNSUBSCRIBE = 'ROUTE_CROSSENGAGE_UNSUBSCRIBE';

    public const CROSSENGAGE_LOCALIZED_CONFIGS = 'CROSSENGAGE_LOCALIZED_CONFIGS';

    public const CROSSENGAGE_CONFIRMATION_PATH = 'CROSSENGAGE_CONFIRMATION_PATH';
    public const CROSSENGAGE_ALREADY_SUBSCRIBED_PATH = 'CROSSENGAGE_ALREADY_SUBSCRIBED_PATH';

    // ROUTE_CROSSENGAGE_SUBSCRIBE
    public const ROUTE_REDIRECT_CROSSENGAGE_SUBSCRIBE = 'ROUTE_REDIRECT_CROSSENGAGE_SUBSCRIBE';
    public const ROUTE_REDIRECT_CROSSENGAGE_SUBSCRIPTION_CONFIRMED = 'ROUTE_REDIRECT_CROSSENGAGE_SUBSCRIPTION_CONFIRMED';
    public const ROUTE_REDIRECT_CROSSENGAGE_ALREADY_SUBSCRIBED = 'ROUTE_REDIRECT_CROSSENGAGE_ALREADY_SUBSCRIBED';
    public const ROUTE_REDIRECT_CROSSENGAGE_UNSUBSCRIBED = 'ROUTE_REDIRECT_CROSSENGAGE_UNSUBSCRIBED';
    public const ROUTE_REDIRECT_CROSSENGAGE_FAILURE = 'ROUTE_REDIRECT_CROSSENGAGE_FAILURE';

    // HashAlgo Constants
    public const CROSSENGAGE_HASH_ALGO = 'CROSSENGAGE_HASH_ALGO';
    public const CROSSENGAGE_MODIFY_IN = 'CROSSENGAGE_MODIFY_IN';
    public const CROSSENGAGE_MODIFY_OUT = 'CROSSENGAGE_MODIFY_OUT';
    public const CROSSENGAGE_MODIFIER_IN = 'CROSSENGAGE_MODIFIER_IN';
    public const CROSSENGAGE_MODIFIER_OUT = 'CROSSENGAGE_MODIFIER_OUT';

    // SprykerUpgradeToDo Check if needed
    public const EDITORIAL_CROSSENGAGE = 'EDITORIAL_CROSSENGAGE';
}
