<?php

namespace FondOfOryx\Client\ReturnLabelsRestApi\Dependency\Client;

use Codeception\Test\Unit;

class ReturnLabelsRestApiToCompanyUserReferenceClientBridgeTest extends Unit
{
    /**
     * @return void
     */
    protected function _before(): void
    {
        parent::_before(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function testFindCompanyUserByCompanyUserReference(): void
    {
    }
}
