<?php

namespace FondOfOryx\Shared\OneTimePassword;

interface OneTimePasswordConstants
{
    public const ONE_TIME_PASSWORD_GERMAN_WORD_LIST_PATH = 'ONE_TIME_PASSWORD:GERMAN_WORD_LIST_PATH';

    public const ONE_TIME_PASSWORD_LOGIN_LINK_PATH = 'ONE_TIME_PASSWORD_LOGIN_LINK_PATH';
    public const ONE_TIME_PASSWORD_LOGIN_LINK_PARAMETER_NAME = 'ONE_TIME_PASSWORD_LOGIN_LINK_PARAMETER_NAME';
    public const ONE_TIME_PASSWORD_LOGIN_LINK_ORDER_REFERENCE_NAME = 'ONE_TIME_PASSWORD_LOGIN_LINK_ORDER_REFERENCE_NAME';
}
