<?php

namespace FondOfOryx\Shared\OneTimePassword;

interface OneTimePasswordConstants
{
    public const ONE_TIME_PASSWORD_GERMAN_WORD_LIST_PATH = 'ONE_TIME_PASSWORD:GERMAN_WORD_LIST_PATH';

    public const ONE_TIME_PASSWORD_AUTO_LOGIN_PATH = 'ONE_TIME_PASSWORD_AUTO_LOGIN_PATH';
    public const ONE_TIME_PASSWORD_AUTO_LOGIN_PARAMETER_NAME = 'ONE_TIME_PASSWORD_AUTO_LOGIN_PARAMETER_NAME';
}
