<?php

namespace FondOfOryx\Client\ProductStyleSearchExpander\Plugin\Elasticsearch\QueryExpander;

use Codeception\Test\Unit;
use Elastica\Query;
use Elastica\Query\BoolQuery;
use Elastica\Query\MatchQuery;
use FondOfOryx\Client\ProductStyleSearchExpander\ProductStyleSearchExpanderFactory;
use FondOfOryx\Shared\ProductStyleSearchExpander\ProductStyleSearchExpanderConstants;
use Spryker\Client\SearchElasticsearch\Query\QueryBuilder;
use Spryker\Client\SearchExtension\Dependency\Plugin\QueryInterface;

class ModelKeyAndStyleKeyQueryExpanderPluginTest extends Unit
{
    /**
     * @var \Spryker\Client\SearchElasticsearch\Query\QueryBuilder|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $queryBuilderMock;

    /**
     * @var \FondOfOryx\Client\ProductStyleSearchExpander\Plugin\Elasticsearch\QueryExpander\ModelKeyAndStyleKeyQueryExpanderPlugin
     */
    protected $queryExpanderPlugin;

    /**
     * @var \FondOfOryx\Client\ProductStyleSearchExpander\ProductStyleSearchExpanderFactory|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $factoryMock;

    /**
     * @var \Elastica\Query|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $elasticaQueryMock;

    /**
     * @var \Spryker\Client\SearchExtension\Dependency\Plugin\QueryInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $searchQueryMock;

    /**
     * @var \Elastica\Query\MatchQuery|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $matchQueryMock;

    /**
     * @var \Elastica\Query\BoolQuery|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $boolQueryMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->factoryMock = $this->getMockBuilder(ProductStyleSearchExpanderFactory::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->searchQueryMock = $this->getMockBuilder(QueryInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->elasticaQueryMock = $this->getMockBuilder(Query::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->boolQueryMock = $this->getMockBuilder(BoolQuery::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->matchQueryMock = $this->getMockBuilder(MatchQuery::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->queryBuilderMock = $this->getMockBuilder(QueryBuilder::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->queryExpanderPlugin = new ModelKeyAndStyleKeyQueryExpanderPlugin();
        $this->queryExpanderPlugin->setFactory($this->factoryMock);
    }

    /**
     * @return void
     */
    public function testExpandQuerySuccess()
    {
        $this->searchQueryMock->expects($this->exactly(1))
            ->method('getSearchQuery')
            ->willReturn($this->elasticaQueryMock);

        $this->factoryMock->expects($this->exactly(2))
            ->method('createQueryBuilder')
            ->willReturn($this->queryBuilderMock);

        $this->elasticaQueryMock->expects($this->once())
            ->method('getQuery')
            ->willReturn($this->boolQueryMock);

        $this->queryBuilderMock->expects($this->exactly(2))
            ->method('createMatchQuery')
            ->willReturn($this->matchQueryMock);

        $this->matchQueryMock->expects($this->exactly(2))
            ->method('setField')
            ->willReturn($this->matchQueryMock);

        $this->queryExpanderPlugin->expandQuery($this->searchQueryMock, [
            ProductStyleSearchExpanderConstants::MODEL_KEY => 'model_key',
            ProductStyleSearchExpanderConstants::STYLE_KEY => 'style_key',
        ]);
    }
}
