<?php

declare(strict_types = 1);

namespace FondOfOryx\Shared\PaymentEpcQrCode;

interface PaymentEpcQrCodeConstants
{
    // Values for the data string within the qr code
    public const EPC_QR_CODE_DATA_VERSION = 'EPC_QR_CODE_DATA_VERSION';
    public const EPC_QR_CODE_DATA_SERVICE_TAG = 'EPC_QR_CODE_DATA_SERVICE_TAG';
    public const EPC_QR_CODE_DATA_ENCODING = 'EPC_QR_CODE_DATA_ENCODING';
    public const EPC_QR_CODE_DATA_TYPE = 'EPC_QR_CODE_DATA_TYPE';
    public const EPC_QR_CODE_DATA_PURPOSE = 'EPC_QR_CODE_DATA_PURPOSE';

    // Values for the qr code
    public const EPC_QR_CODE_QR_CODE_FORMAT = 'EPC_QR_CODE_QR_CODE_FORMAT';
    public const EPC_QR_CODE_QR_CODE_ENCODING_OVERRIDE = 'EPC_QR_CODE_QR_CODE_ENCODING_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_ERROR_CORRECTION_LEVEL_OVERRIDE = 'EPC_QR_CODE_QR_CODE_ERROR_CORRECTION_LEVEL_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_SIZE_OVERRIDE = 'EPC_QR_CODE_QR_CODE_SIZE_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_MARGIN_OVERRIDE = 'EPC_QR_CODE_QR_CODE_MARGIN_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_FOREGROUND_COLOR_OVERRIDE = 'EPC_QR_CODE_QR_CODE_FOREGROUND_COLOR_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_ROUNDED_BLOCK_SIZE_MODE_OVERRIDE = 'EPC_QR_CODE_QR_CODE_ROUNDED_BLOCK_SIZE_MODE_OVERRIDE';
    public const EPC_QR_CODE_QR_CODE_BACKGROUND_COLOR_OVERRIDE = 'EPC_QR_CODE_QR_CODE_BACKGROUND_COLOR_OVERRIDE';
}
