<?php

namespace FondOfOryx\Client\ReturnLabelsRestApi\Zed;

use Codeception\Test\Unit;

class ReturnLabelsRestApiZedStubTest extends Unit
{
    /**
     * @return void
     */
    protected function _before(): void
    {
        parent::_before(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function testGetReturnLabel(): void
    {

    }

    /**
     * @return void
     */
    public function testFindCompanyUnitAddressByExternalReference(): void
    {

    }
}
