<?php

namespace FondOfOryx\Zed\ReturnLabelsRestApi\Business;

use Codeception\Test\Unit;

class ReturnLabelsRestApiFacadeTest extends Unit
{
    /**
     * @return void
     */
    protected function _before(): void
    {
        parent::_before(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function testFindCompanyUnitAddressByExternalReference(): void
    {
    }

    /**
     * @return void
     */
    public function testGetReturnLabel(): void
    {
    }
}
